[package]
name = "timeout"
version = "0.1.0"
authors = ["Camden Narzt <c.narzt@me.com>"]
edition = "2018"

[dependencies.futures]
version = "0.3"

[dependencies.tokio]
version = "1.35"
features = [ "time", "process", "rt", "rt-multi-thread", "macros" ]
